### get all seasons
GET http://localhost:8080/webapi/test/seasons

### get season by id
GET http://localhost:8080/webapi/test/seasons/1

### kierowcy na sezon 2026
GET http://localhost:8080/webapi/test/driverEntries

### zespoły na 2026
GET http://localhost:8080/webapi/test/teamEntries

### wszystkie zespoly
GET http://localhost:8080/webapi/test/teams

### pojedynczy zespol
GET http://localhost:8080/webapi/test/teams/6

### pojedynczy kierowca
GET http://localhost:8080/webapi/test/drivers/2



### team entry przez driver entry
GET http://localhost:8080/webapi/driverEntries/2/teamEntry
Accept: application/json


### wyszukanie wraz z imieniem i nazwiskiem
GET http://localhost:8080/webapi/driver?firstName=Charles&lastName=Leclerc
custom-header: costam

### dodanie kierowcy
POST http://localhost:8080/webapi/drivers
Content-Type: application/json

{
  "firstName": "Michael",
  "lastName": "Schumacher",
  "age": 60,
  "country": "Germany"
}

### NULL w imieniu
POST http://localhost:8080/webapi/drivers
Content-Type: application/json
Accept-Language: pl

{
"age": 60,
"country": "Germany"
}

### za dlugie
POST http://localhost:8080/webapi/drivers
Content-Type: application/json

{
  "firstName": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "lastName": "BBB",
  "age": 60,
  "country": "Germany"
}




### adding driverEntry
POST http://localhost:8080/webapi/driverEntries
Content-Type: application/json

{
  "driverId": 3,
  "teamEntryId": 2,
  "number": 21
}
