### get all seasons
GET http://localhost:8080/webapi/test/seasons

### get season by id
GET http://localhost:8080/webapi/test/seasons/1

### kierowcy na sezon 2026
GET http://localhost:8080/webapi/test/driverEntries

### zespoły na 2026
GET http://localhost:8080/webapi/test/teamEntries

### wszystkie zespoly
GET http://localhost:8080/webapi/test/teams

### pojedynczy zespol
GET http://localhost:8080/webapi/test/teams/4

### pojedynczy kierowca
GET http://localhost:8080/webapi/test/drivers/2



### team entry przez driver entry
GET http://localhost:8080/webapi/driverEntries/2/teamEntry
Accept: application/json


### wyszukanie wraz z imieniem i nazwiskiem
GET http://localhost:8080/webapi/driver?firstName=Charles&lastName=Leclerc
custom-header: costam

### dodanie kierowcy
POST http://localhost:8080/webapi/drivers
Content-Type: application/json

{
  "firstname": "Michael",
  "lastname": "Schumacher",
  "country": "Germany"
}

### dodanie kierowcy z data urodzenia
POST http://localhost:8080/webapi/drivers
Content-Type: application/json

{
  "firstname": "Jan",
  "lastname": "Kowalski",
  "country": "Poland",
  "birthDate": "2000-01-01"
}

### rollback przy dodawaniu kierowcy
POST http://localhost:8080/webapi/drivers
Content-Type: application/json

{
  "firstname": "Rollback",
  "lastname": "Kowalski",
  "country": "Poland",
  "birthDate": "2000-01-01"
}

### NULL w imieniu
POST http://localhost:8080/webapi/drivers
Content-Type: application/json
Accept-Language: pl

{
"country": "Germany"
}

### za dlugie
POST http://localhost:8080/webapi/drivers
Content-Type: application/json

{
  "firstname": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "lastname": "BBB",
  "country": "Germany"
}




### adding driverEntry
POST http://localhost:8080/webapi/driverEntries
Content-Type: application/json

{
  "driverId": 3,
  "teamEntryId": 2,
  "number": 21
}

### actuator root
GET http://localhost:8080/actuator

### actuator health
GET http://localhost:8080/actuator/health

### actuator env
GET http://localhost:8080/actuator/env

### actuator beans
GET http://localhost:8080/actuator/beans

### actuator info
GET http://localhost:8080/actuator/info

### actuator shutdown
POST http://localhost:8080/actuator/shutdown

### security: get teams without login
GET http://localhost:8080/webapi/test/teams

### security: create team without login -> 401
POST http://localhost:8080/webapi/teams
Content-Type: application/json

{
  "name": "Security Test Team",
  "cityLocation": "Warsaw",
  "country": "Poland"
}

### security: create team with invalid user -> 401
POST http://localhost:8080/webapi/teams
Content-Type: application/json
Authorization: Basic d3Jvbmc6d3Jvbmc=

{
  "name": "Security Test Team",
  "cityLocation": "Warsaw",
  "country": "Poland"
}

### security: create team as user without admin role -> 403
POST http://localhost:8080/webapi/teams
Content-Type: application/json
Authorization: Basic ZGJ1c2VyMjpkYnVzZXIy

{
  "name": "Security Test Team",
  "cityLocation": "Warsaw",
  "country": "Poland"
}

### security: create team as admin -> 201
POST http://localhost:8080/webapi/teams
Content-Type: application/json
Authorization: Basic ZGJ1c2VyMTpkYnVzZXIx

{
  "name": "Security Test Team",
  "cityLocation": "Warsaw",
  "country": "Poland"
}

### security: create driver as admin -> 201
POST http://localhost:8080/webapi/drivers
Content-Type: application/json
Authorization: Basic ZGJ1c2VyMTpkYnVzZXIx

{
  "firstname": "Security",
  "lastname": "Driver",
  "country": "Poland",
  "birthDate": "2001-01-01"
}
