### getting team
GET http://localhost:8080/webapi/teams
Content-Type: application/json

### adding team
POST http://localhost:8080/webapi/teams
Content-Type: application/json

{
  "name": "Alpine",
  "cityLocation": "Enstone",
  "country": "United-Kingdom"

}